
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      The target system is: Generic - 3.7.99 - riscv
      The host system is: Linux - 6.8.0-52-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /home/davit/zephyr-sdk-0.16.8/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/davit/Desktop/sim/build_sim/CMakeFiles/3.31.2/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /home/davit/zephyr-sdk-0.16.8/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/davit/Desktop/sim/build_sim/CMakeFiles/3.31.2/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/kernel.cmake:134 (enable_language)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      riscv64-zephyr-elf-gcc (Zephyr SDK 0.16.8) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      The target system is: Generic - 3.7.99 - riscv
      The host system is: Linux - 6.8.0-60-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /home/davit/zephyr-sdk-0.16.8/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/davit/Desktop/sim/build_sim/CMakeFiles/3.31.6/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /home/davit/zephyr-sdk-0.16.8/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/davit/Desktop/sim/build_sim/CMakeFiles/3.31.6/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/kernel.cmake:134 (enable_language)"
      - "/home/davit/Desktop/sim/zephyr/cmake/modules/zephyr_default.cmake:142 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/davit/Desktop/sim/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "CMakeLists.txt:12 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      riscv64-zephyr-elf-gcc (Zephyr SDK 0.16.8) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
